### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by fippli** [fippli/terminal-todo#17]
Would be nice to refactor a bit and separate the code into several files to not have a huge monolith bash script. Im thinking something like:
```
root
|
└ src
   | 
   └ main.sh
   └ options
   | └ todo_from_file.sh
   └ templates
     └ table_head.sh
|
└ Makefile
└ README.md
... etc
```

**Comment by bombsimon** [comment]
As far as I can tell the code is already split like your tree shows but the files are in the root directory. I think this is common and follows common project structures for this kind of projects. For inspiration see [trending shell](https://github.com/trending/shell), e.g. [nvm (Node Version Manager)](https://github.com/nvm-sh/nvm). Of course you could still structure it to your flavour anyway!

It's not related to project structure but I also found [this article](https://kvz.io/bash-best-practices.html) yesterday which mentions some nice patters (that I forgot), i.e. `set -eux`. :)

**Comment by fippli** [comment]
Nice! Thanks for the article :) I will read it! Would be nice to learn bash a little better :)

**Comment by bombsimon** [comment]
Then I would also recommend [this repository](https://github.com/dylanaraps/pure-bash-bible). I sometimes forget how much you can do with pure bash!

**Comment by fippli** [comment]
Haha! Speaking of: "9. Surround your variables with {}. Otherwise bash will try to access the $ENVIRONMENT_app variable in /srv/$ENVIRONMENT_app, whereas you probably intended /srv/${ENVIRONMENT}_app."

**Comment by bombsimon** [comment]
Hehe, yeah exactly! That's what I tried to explain but I only use it when it's combined with a string or other variable. But I guess it's better use the same syntax everywhere. 🤔

**Comment by fippli** [comment]
I try to follow the consistency principle but I don't care that much :)

**Comment by fippli** [comment]
I care more when  it comes to big projects where a lot of people are involved. But for a little hobby project like this I'd say whatever is fine.

**Comment by bombsimon** [comment]
Yeah me too! 😸

Just to make it clear my contributions here (code/issues/PRs) are tongue-in-cheek and I don't care either, although I see no reasons to not follow known best practices. Also I'm so used to work with issue tracking, PRs, code conventions etc so it's a bit automatic for me and hard to not appear too serious when it's out in the public like GitHub is. 👨‍🏫 

Btw, if we're working on implementations can we make sure to assign the issues to avoid double the work? Not because I care about doing the work twice but because I don't like to resolve merge conflicts 💃

**Comment by fippli** [comment]
Sure! I just forgot doing it last time :) Usually do it. I'm currently busy so go ahead if you're on fire!!! Ill probably look more into all updates this weekend :)

**Comment by fippli** [comment]
Ill split the code a bit for #18 otherwise it will be too messy 😛
