### ISSUE TITLE
Idea: Arrow navigation instead of entering task number

### ISSUE THREAD

**Issue by fippli** [fippli/terminal-todo#18]
The selected task should be bold and arrow up/down selects the task above/below the current

**Comment by bombsimon** [comment]
Yeah I was thinking about this as well. But I guess it depends on your end goal. Learning new things? Being smart? Creating an actual good app (sadly there are plenty CLI TODOs out there so I guess that's that)?

I did a google search yesterday about implementing something like `ncurses` with bash which seems to be fairly easy. But then again you add yet another dependency.

If you see this as a fun learning experience to dig deeper into bash I think this is fine but if not I think there are plenty other solutions to implement TUI! :)

**Comment by fippli** [comment]
Yeah I don't know really. I don't expect this to be a top seller on any market soon. I just want it to be useful and nice for me to use. Lets see, there might be some simple implementation that is not too complex and doesn't involve dependencies.

**Comment by bombsimon** [comment]
Hehe, you don't? At least if you run `npm create-react-app` in your terminal you'll have a startup (and maybe investors?!)

Let's do this then, curses is kinda common anyways. :)

**Comment by fippli** [comment]
Haha lets talk to [this guy](https://github.com/tianyicui). [http://todo.sh](http://todo.sh) points to his website. Then we can talk about startups when we have access to that domain :)

Do you know if the arrow keypress is registered and passed to a variable while doing something like `read -p "blabla" input`? Then maybe the selction can be stored in the `.todo` like 
```
item 1
->item 2
item 3
```
and just edit the file on keypress?

**Comment by fippli** [comment]
Or
```
[] item 1
[x] item 2
[] item 3
```
so that `->` also can be used as a string in the todo

**Comment by bombsimon** [comment]
Yeah you can read the keas but it's kind of dependent on the terminal emulator and OS etc.

First off, you can read the key without requiring enter by using `-s`. We should actually change the selection prompts to this:

```sh
echo -n "       [A]DD / [D]ELETE / [E]DIT / [Q]UIT : "
read -s -n 1 choice
```

This will trigger the assignment to choice at keypress.

I think you just have to match the `$choice` towards the escape sequence of arrow keys to determine if an arrow was pressed. [This post](https://stackoverflow.com/questions/10679188/casing-arrow-keys-in-bash) looks promising. :)

**Comment by fippli** [comment]
Sure. Either we just add all the possible variants. Or! It becomes quite neat if you think about it:
```
// keyboard layout
qwe...
asd...
```
q - quit
w - up
e - edit
a - add
s - down
d - delete
All navigation is in the same location on the keyboard. This could also be configured I guess. I'm probably the only one left using **qwerty**...

**Comment by bombsimon** [comment]
Hehe, I think most still use qwerty. :) However, I tend to use vim bindings (hjkl) in all applications that support it. It's also a kind of common pattern.

So, w/k -> up, s/l -> down?

**Comment by fippli** [comment]
Perfect!

**Comment by fippli** [comment]
I'll give this a go :)
