### ISSUE TITLE
Include other files according to best practices

### ISSUE THREAD

**Issue by bombsimon** [fippli/terminal-todo#26]
See [How to best include other script?](https://stackoverflow.com/questions/192292/how-best-to-include-other-scripts) Other files/scripts shouldn't be executed with `bash`, there should be a function defined in the related file and after it's been sourced, that function should be called. Example:

```sh
$ tail {one,two}.sh
==> one.sh <==
#!/usr/bin/env bash

. two.sh

one_var="this is var"

func_from_two

==> two.sh <==
#!/usr/bin/env bash

func_from_two() {
    echo "This is two with variable from one: '$one_var'"
}
```

```sh
$ ./one.se
This is two with variable from one: 'this is var'
```

---
From #25:

I would make all the bash files executable and source the other bash files. By just writing bash you assume that the caller wants to use the first bash in PATH which might not be the case.

Try these:

```sh
$ tail -n99 {one,two}.sh
==> one.sh <==
#!/usr/bin/env bash

echo "BASH_VERSION in one.sh"
echo "$BASH_VERSION"
echo ""

echo "Using bash first in PATH"
bash two.sh
echo ""

echo "Using /bin/bash"
/bin/bash two.sh
echo ""

echo "Using shebang (/usr/bin/env bash)"
/usr/bin/env bash two.sh
echo ""

echo "Sourcing second file (keep binary)"
. two.sh
echo ""

==> two.sh <==
#!/usr/bin/env bash

echo "BASH_VERSION in two.sh"
echo "$BASH_VERSION"
```

And compare:

* `/bin/bash one.sh`
* `bash one.sh`
* `./one.sh`
* `/usr/bin/env bash one.sh`

Depending on your system and setup you'll get quite different results. You probably want to do the last one and source the other files.

**Comment by fippli** [comment]
Ah! Ok, then I understand what you mean :)

**Comment by fippli** [comment]
So do we just include all the files at the top of the main file like 
```
#!/usr/bin/env bash

. two.sh
. three.sh
. four.sh
...more files

```
to include the functions from other files?

**Comment by bombsimon** [comment]
Yup, just like an `import` statement! And maybe it's obvious but there should probably don't be any code in the global scope of the sourced files but rather in functions you want to access.

Multiple files can source the same files which might not be necessary but improve readability if `two.sh` and `three.se` both uses a function form `utils.sh`, they should probably be imported in both. :)

**Comment by fippli** [comment]
Perfect! I've been wondering how this is done in a good way i bash. Now I know.
