### ISSUE TITLE
Change variables to be lowercase to not confuse with bash enviroment variables

### ISSUE THREAD

**Issue by fippli** [fippli/terminal-todo#4]
E.g. `CHOICE` and `TASK`

**Comment by bombsimon** [comment]
Regarding conventions, functions should not use both the `function` keyword and `()`. According to the first Google hit I found the preferred one is `()` without `function`[[1]](https://linuxize.com/post/bash-functions/) keyword. This is also the one I prefer :)

Also, it seems like CamelCase isn't the recommended convention for filenames[[2]](https://unix.stackexchange.com/questions/7351/unix-file-naming-convention) so maybe `tableHead.sh` should be `table_head.sh`?

**Comment by fippli** [comment]
I agree. This is probably just a habit from coding too much JavaScript. My bash conventions knowledge is quite limited. I am all for changing the code to be more aligned with the conventions.
