### ISSUE TITLE
Use asciinema for demo

### ISSUE THREAD

**Issue by bombsimon** [fippli/terminal-todo#9]
Instead of checking in the gif we could use [asciinema](https://asciinema.org/).

Here's an example recording demoing the application: https://asciinema.org/a/7n6nHB7hbfNZhNmpP0CVepLMO

This can be embedded in markdown like this:

```markdown
[![asciicast](https://asciinema.org/a/7n6nHB7hbfNZhNmpP0CVepLMO.svg)](https://asciinema.org/a/7n6nHB7hbfNZhNmpP0CVepLMO)
```

[![asciicast](https://asciinema.org/a/7n6nHB7hbfNZhNmpP0CVepLMO.svg)](https://asciinema.org/a/7n6nHB7hbfNZhNmpP0CVepLMO)

**Comment by fippli** [comment]
Awesome! Lets do that!
